services:
  db:
    environment:
      POSTGRES_PASSWORD: postgres
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    depends_on:
      - db
    ports:
      - "3001:3001"
    volumes:
      - .:/app:delegated
version: '3'